apiVersion: kubeflow.org/v2beta1
kind: MPIJob
metadata:
  name: openmpi-job
spec:
  slotsPerWorker: 1
  runPolicy:
    cleanPodPolicy: Running
    activeDeadlineSeconds: 300
  mpiImplementation: OpenMPI
  mpiReplicaSpecs:
    Launcher:
      replicas: 1
      template:
        spec:
          hostname: openmpi-master
          containers:
          - name: openmpi-launcher
          securityContext:
            runAsUser: 1000
            image: k8sschool/openmpi
            command: ["mpirun"]
            args: ["-np", "3", "./mpi_hello_world"]
            resources:
              requests:
                memory: "256Mi"
                cpu: "250m"
              limits:
                memory: "512Mi"
                cpu: "500m"
          restartPolicy: Never
    Worker:
      replicas: 3
      template:
        spec:
          containers:
          - name: openmpi-worker
            image: k8sschool/openmpi
            securityContext:
              runAsUser: 1000
            command:
            - /usr/sbin/sshd
            args:
            - -De
            - -f
            - /home/mpiuser/.sshd_config
            resources:
              requests:
                memory: "256Mi"
                cpu: "250m"
              limits:
                memory: "512Mi"
                cpu: "500m"
          restartPolicy: Never
