apiVersion: kubeflow.org/v2beta1
kind: MPIJob
metadata:
  name: openmpi-job
spec:
  slotsPerWorker: 1
  runPolicy:
    cleanPodPolicy: Running
    ttlSecondsAfterFinished: 60
  sshAuthMountPath: /home/mpiuser/.ssh
  mpiImplementation: OpenMPI
  mpiReplicaSpecs:
    Launcher:
      replicas: 1
      template:
        spec:
          hostname: openmpi-master
          containers:
          - name: openmpi-launcher
            securityContext:
              runAsUser: 1000
            image: k8sschool/k8s-mpi-openmpi
            command: ["mpirun"]
            args:
              - -n
              - "2"
              - /home/mpiuser/pi
            resources:
              requests:
                memory: "256Mi"
                cpu: "250m"
              limits:
                memory: "512Mi"
                cpu: "500m"
    Worker:
      replicas: 2
      template:
        spec:
          containers:
          - name: openmpi-worker
            image: k8sschool/k8s-mpi-openmpi
            securityContext:
              runAsUser: 1000
            command:
            - /usr/sbin/sshd
            args:
            - -De
            - -f
            - /home/mpiuser/.sshd_config
            resources:
              requests:
                memory: "256Mi"
                cpu: "250m"
              limits:
                memory: "512Mi"
                cpu: "500m"
